### ISSUE TITLE
Is there a way to add custom text at any position?

### ISSUE THREAD

**Issue by s7dhansh** [classdojo/photo-mosaic#1]
I don't think the library supports it (unless I have an image with the text), but I was wondering if you could guide me to a way of achieving that through canvas.

**Comment by s7dhansh** [comment]
So I have figured out the text part. The code's at
https://github.com/settlin/photo-collage

I am not sure if my coding style is same as yours (especially the options part), but if you agree with it, I can add a PR.

**Comment by peterkhayes** [comment]
Looks pretty good!  I've left the library pretty minimal, because you get the canvas object back and can always roll your own stuff on top, but the text feature seems pretty common and worth setting up.  Open a PR and I'll do a more detailed CR.

**Comment by s7dhansh** [comment]
done https://github.com/classdojo/photo-collage/pull/2

**Comment by s7dhansh** [comment]
@peterkhayes can you publish the update please

**Comment by s7dhansh** [comment]
@peterkhayes please npm publish the update
