### ISSUE TITLE
No license provided

### ISSUE THREAD

**Issue by RectangleEquals** [classdojo/photo-mosaic#4]
Please include a license to make it legal to use and/or modify this code.

From https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

"If a repository has no license, then all rights are reserved and it is not Open Source or Free. You cannot modify or redistribute this code without explicit permission from the copyright holder.
...
In short, the only thing you can safely assume is that you have no rights to do anything at all with this code. In the particular case of GitHub, you can fork the repository and view the code, but nothing more."

**Comment by dbellizzi** [comment]
Fixed, thanks for bringing it to our attention
